version: '3.7'
services:
  api:
    build: ./
    command: poetry run python ./src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '25566:8000'
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - '5432:5432'

volumes:
  pg_data: